language: node_js
node_js:
  - 10
  - 12
  - node
services:
  - docker
git:
  depth: false
  quiet: true
cache:
  directories:
  - "$HOME/.npm"
install:
  - npm install -g codecov
  - npm ci
script:
  - npm run test-integration
  - npm run lint
  - codecov
jobs:
  include:
    - stage: docker build
      node_js: node
      script:
        - npm ci --prod
        - docker build --rm -t "${DOCKER_USERNAME}/${DOCKER_IMAGE}:latest" -t "${DOCKER_USERNAME}/${DOCKER_IMAGE}:git$(git rev-parse --short HEAD)" .
    - stage: docker push
      node_js: node
      if: branch = master
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - npm ci --prod
        - docker build -t "${DOCKER_USERNAME}/${DOCKER_IMAGE}:latest" -t "${DOCKER_USERNAME}/${DOCKER_IMAGE}:git$(git rev-parse --short HEAD)" .
        - docker push "${DOCKER_USERNAME}/${DOCKER_IMAGE}:latest"
        - docker push "${DOCKER_USERNAME}/${DOCKER_IMAGE}:git$(git rev-parse --short HEAD)"
